# SPDX-License-Identifier: MIT-0
---
# tasks file for website

# tasks/main.yml

- name: Update apt cache
  apt:
    update_cache: yes

- name: Install Nginx
  apt:
    name: nginx
    state: present

- name: Ensure Nginx service is running and enabled
  service:
    name: nginx
    state: started
    enabled: yes

- name: Ensure website path exists
  file:
    path: /var/www/html
    state: directory
    owner: www-data
    group: www-data
    mode: '0755'

- name: Copy Website Template
  template:
    src: index.html.j2
    dest: /var/www/html/index.html
    owner: www-data
    group: www-data
    mode: '0644'
