# SPDX-License-Identifier: MIT-0
---
# tasks file for website

- name: Ensure website path exists
  ansible.builtin.file:
    path: /var/www/html
    state: directory
    owner: www-data
    group: www-data
    mode: '0755'

- name: Copy Website Template
  ansible.builtin.template:
    src: index.html.j2
    dest: /var/www/html/index.html
    owner: www-data
    group: www-data
    mode: '0644'

- name: Run Nginx container with mounted website
  community.docker.docker_container:
    name: mywebsite
    image: nginx:latest
    state: started
    restart_policy: always
    ports:
      - "80:80"
    volumes:
      - "/var/www/html:/usr/share/nginx/html"
