#SPDX-License-Identifier: MIT-0
---
# tasks file for website
- name: Ensure website path exist
  file:
    path: /var/www/html
    state: directory
    owner: www-data
    group: www-data
    mode: '0755'
- name: Copy Website Template
  template:
    src: index.html.j2
    desc: /var/www/html/index.html
    owner: www-data
    group: www-data
    mode: '0644'
- name: Pull Nginx Image from DockerHub
  community.docker.docker_image:
   name: mywebsite
   image: nginx:latest
   state: started
   ports:
    - "80:80"
  volumes:
    - "/var/www/html:/usr/share/nginx/html"
  restart_policy: always

